### ISSUE TITLE
Date range does not work

### ISSUE THREAD

**Issue by ff00005** [ascii-dresden/asciii#109]
For caterings spanning multiple days, clients require the date range to be correctly printed on their invoice. The `begin`-portion of the event works fine, `end` does not. The corresponding config-file region looks like this:

```
event:
  name: Stehtische CIDS-Fest
  location: # might be a list
  dates:
  - begin: 05.06.2024
    end: 07.06.2024
    times:
    -  begin: ""
       end:   ""
```

Setting the `end` parameter does nothing, the corresponding invoice text (and probably offer text as well) looks this way:

`wir bedanken uns für Ihren Auftrag für das Catering am 05.06.2024 und erlauben uns Ihnen folgende Rechnung zu stellen:`

Rather, it should be changed to

`wir bedanken uns für Ihren Auftrag für das Catering vom 05. bis 07.06.2024 und erlauben uns Ihnen folgende Rechnung zu stellen:`
