### ISSUE TITLE
Catch wrong Invoice Number Format

### ISSUE THREAD

**Issue by V1ncNet** [ascii-dresden/asciii#81]
`asciii make` will fail without describing error message when invoice number got the wrong format.
This issue will apply on other properties from the project yaml too.

```yaml
invoice:
  number: R010 ## <- This will fail
  date: 26.02.2018
  payed_date:
  official:
```
